### PR TITLE
Added capabilities to save generated objects into editor READ THE COMMENT

### PR DESCRIPTION
**Pull request by Asduffo**
Disclaimer: I'm a total noob at github and that's the first time i did a pull request but anyway:
I added a new function which allows to load the fmdl and save it into the assets folder (it requires to have a folder named Saved_models in the assets folder) so you won't have to reload it every time and should be good for modding too. Before this, just dragging the generated gameobject into the asset folder wouldn't save the meshes. In theory it should allow some script such as the infamous Obj_Exporter to export the mesh files as .obj too but I didn't try it yet.
Please note that altrough it works, saving the material too might cause some exceptions (just comment the row where it saves the material) BUT it will still save it without problem for some reason (lol)

**STILL there is an huge issue:**
Altrough I'm using the latest commit, I found the entire fmdl studio to be broken and stopped working with both PT and MGSV models (will open an issue).
I've actually developed the saving system with the commit named **"Fixed bounding box size issue. Root bone is now created."** which I think is the last one who used to work but I think that there shouldn't be any problems at all with it once the issue with the studio itself is solved.

### CODE REVIEW

**Comment by BobDoleOwndU** [comment]
We're holding off saving assets for now as the plan is to export the models as .fbx files. From there, the models can be edited in any 3D modelling software and exported back to .fbx files, which Fmdl Studio will then be able to load and export .fmdls from.

In regards to the issue, it should be fixed in my latest commit. I'm not sure which commit broke it; but with my latest commit, it's working fine again.

**Comment by Asduffo** [comment]
Mh ok.
PS: didn't try with MGSV models cause I only partially disassembled the game, but are textures applied correctly there? Because with PT models the textures used to be applied correctly but now they are applied upside down, like rotated 180 degrees :/

**Comment by BobDoleOwndU** [comment]
The textures are applied fine with the MGSV models as far as I can tell. The stuff relating to how the texture coordinates are applied hasn't been touched. I think PT models just use the GZ model format, which the tool can apply textures to without issue. So I'm not sure what would cause it to break with the PT models.

**Comment by Asduffo** [comment]
Btw will you keep working into the fbx exportation now that unity 2017.2 with the autodesk partnership added full export/import functionalities?

**Comment by BobDoleOwndU** [comment]
Unfortunately, it looks like the Unity exporter doesn't support rigging. So we're either going to need to write one ourselves, or find one that does support it.

**Pull request closed without merging**
